WIP: Create Signup Screen UI
muammerakca10/CactusNotes pull request #1
Opened 2021-03-19 08:29 UTC by muammerakca10

2021-03-22 08:01 UTC, safaorhan requested changes
First iteration of my feedback is done!

Try to address all of my comments and try to find areas where you could apply the same suggestions.

2021-03-22 17:26 UTC, cmfndkl commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            !passwordSpaceControl(password) -> "Password cannot contain space."
User visible strings should always be extracted into strings.xml.

2021-03-22 17:26 UTC, cmfndkl commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:textSize="14sp" />
All buttons must be MaterialButtons.

2021-03-24 14:19 UTC, safaorhan commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:textSize="14sp" />
All buttons must be MaterialButtons that's correct. However, if the theme of the app extends from a MaterialComponents theme, then Button -> MaterialButton conversion is done automatically.

Check: https://stackoverflow.com/questions/57925853/is-any-difference-between-a-materialbutton-and-a-simple-button

2021-03-24 17:10 UTC, muammerakca10 commented on app/src/main/AndroidManifest.xml
> +            android:label="@string/signUp_activity_name">
Done

2021-03-25 22:50 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        //Email Control Start
Thank you for feedback. I made the necessary corrections.

2021-03-25 22:50 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            !emailNullEmptyControl(email) -> "Email is required."
Thank you for feedback. I made the necessary corrections.

2021-03-25 22:50 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            //username!!.contains("[a-z][0-9]_") seklinde de yazilabilir mi?
Thank you for feedback. I made the necessary corrections.

2021-03-25 22:54 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +                textInputEmail.editText!!.text.toString() //bosluklara hassasiyeti artirmak icin trimleri kaldirdim
Thank you for feedback. I made the necessary corrections.

2021-03-25 22:55 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:textSize="14sp" />
Thank you for feedbacks.

2021-03-25 22:55 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-25 22:56 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-25 22:56 UTC, muammerakca10 commented on app/src/main/res/values/strings.xml
> +    <string name="signupActivity">Sign up</string>
Thank you for feedback. I made the necessary corrections.

2021-03-25 23:18 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-25 23:18 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-25 23:20 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            !passwordSpaceControl(password) -> "Password cannot contain space."
Thank you for feedback. I made the necessary corrections.

2021-03-25 23:21 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        fun passwordNullOrEmptyControl(password: String): Boolean {
Thank you for feedback. I made the necessary corrections.

2021-03-26 16:51 UTC, safaorhan requested changes
Well done! 🥳 

There are some critical and some minor problems, we should do another iteration!

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        //Email Error Messages Start
We can remove these comment lines

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        } //Email Error Messages Finish
We can remove these comment lines

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        //Button Click Start
We can remove these comment lines

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        fun emailErrorMessages(email: String) = when {
We can rename this into `validateEmail(email: String)`

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        fun usernameErrorMessages(username: String) = when {
This as well, validateUsername...

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        fun passwordErrorMessages(password: String) = when {
...validatePassword...

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            !password.any { it.isDigit() } || !password.any { it.isDigit() } || !password.any { it.isLowerCase() } || !password.any { it.isLetterOrDigit() } -> getString(R.string.password_must_contai
1. `!password.any { it.isDigit() }` is checked twice.
2. We can extract those into functions for better readability

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            !password.any { it.isDigit() } || !password.any { it.isDigit() } || !password.any { it.isLowerCase() } || !password.any { it.isLetterOrDigit() } -> getString(R.string.password_must_contai
`fun String.containsDigit() = any { it.isDigit() }`
...
`!password.containsDigit() || !p...`

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            !password.any { it.isDigit() } || !password.any { it.isDigit() } || !password.any { it.isLowerCase() } || !password.any { it.isLetterOrDigit() } -> getString(R.string.password_must_contai
`!password.any { it.isLetterOrDigit() }` checks if it does not contain any "letter or digit" but instead you should check:

`!password.any { !it.isLetterOrDigit() }` checks if it does not contain any character which is not "letter or digit"

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/res/layout/activity_sign_up.xml
> +
No new-lines before closing tag

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/res/layout/activity_sign_up.xml
> +
No new-lines before closing tag

2021-03-26 16:51 UTC, safaorhan commented on app/src/main/res/values/strings.xml
> +    <string name="signupActivity">Sign_Up</string>
casing and fix user visible strings

2021-03-27 11:27 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        //Email Error Messages Start
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:27 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        } //Email Error Messages Finish
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:30 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        fun emailErrorMessages(email: String) = when {
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:30 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        fun usernameErrorMessages(username: String) = when {
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:30 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        fun passwordErrorMessages(password: String) = when {
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:32 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:32 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:40 UTC, muammerakca10 commented on app/src/main/res/values/strings.xml
> +    <string name="signupActivity">Sign_Up</string>
Thank you for feedback. I made the necessary corrections.

2021-03-27 11:59 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +        //Button Click Start
Thank you for feedback. I made the necessary corrections.

2021-03-27 12:51 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-27 12:51 UTC, muammerakca10 commented on app/src/main/res/layout/activity_sign_up.xml
> +
Thank you for feedback. I made the necessary corrections.

2021-03-27 14:23 UTC, muammerakca10 commented on app/src/main/java/com/muammerakca/cactusnotes/SignUpActivity.kt
> +            !password.any { it.isDigit() } || !password.any { it.isDigit() } || !password.any { it.isLowerCase() } || !password.any { it.isLetterOrDigit() } -> getString(R.string.password_must_contai
Thank you for feedback. I made the necessary corrections.

2021-03-30 09:53 UTC, safaorhan approved these changes
Looks good to me! We can merge this after this gets QAed

2021-03-30 21:25 UTC, cmfndkl commented
Congratulations, nice job. However, you have to make some changes: 
- Password visibility is default enabled. You should make your password visibility invisible by default.  
- The "Already Have Account" button should be changed to "material button" and should be the same width as the "SIGN UP" button.

2021-04-02 04:09 UTC, safaorhan commented
@cmfndkl we already discussed the material button thing earlier.

If you use a MaterialComponents theme, Button -> MaterialButton conversion is done automatically. So no need to use MaterialButtons in the XML explicitly.

2021-04-06 16:49 UTC, safaorhan approved these changes

2021-04-06 16:50 UTC, merged